#!/usr/bin/env python3

import argparse
import json
import os
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('--json', type=json.loads, required=True, help='the args')

# Parse the args
args, unknown = parser.parse_known_args()

collection = args.json['collections'][0]
name, path = collection["name"], collection["path"]

subprocess.run("""
		/bin/sh ../work/anserini/target/appassembler/bin/IndexCollection -collection TrecCollection \
		-generator JsoupGenerator -threads {0} -input {1} -index \
		lucene-index.{2}.pos+docvectors+rawdocs -storePositions -storeDocvectors \
		-storeRawDocs
    """.format(os.cpu_count(), path, name).split())