#!/usr/bin/env python3

import argparse
import json
import os
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('--json', type=json.loads, required=True, help='the args')

# Parse the args
args, unknown = parser.parse_known_args()

# Indexing options for robust04
index_options = {
    "robust04": {
        "collection": "TrecCollection",
        "generator": "JsoupGenerator"
    }
}

for collection in args.json["collections"]:
    name, path = collection["name"], collection["path"]
    collection, generator = index_options[name]["collection"], index_options[name]["generator"]

    subprocess.run("""
            /bin/sh anserini/target/appassembler/bin/IndexCollection -collection {0} \
            -generator {1} -threads {2} -input {3} -index \
            lucene-index.{4}.pos+docvectors+rawdocs -storePositions -storeDocvectors \
            -storeRawDocs
        """.format(collection, generator, os.cpu_count(), path, name).split())
