#!/usr/bin/env bash

echo "Initializing..."

# Clone Anserini
git clone https://github.com/castorini/anserini.git
chmod -R +x anserini
cd anserini
mvn clean package appassembler:assemble
cd eval
tar xvfz trec_eval.9.0.4.tar.gz && cd trec_eval.9.0.4 && make
cd ../../..

# Install Apex
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir .
cd ../birch

# Download data
mkdir -p data/datasets
curl -o data/datasets/robust04.csv "https://www.googleapis.com/download/storage/v1/b/birch_data/o/datasets%2Frobust04_test.csv?alt=media"

# Download models
mkdir models
curl -o models/saved.mb_3 "https://www.googleapis.com/download/storage/v1/b/birch_data/o/birch_models%2Fsaved.mb_3?alt=media"
curl -o models/saved.qa_2 "https://www.googleapis.com/download/storage/v1/b/birch_data/o/birch_models%2Fsaved.qa_2?alt=media"