#!/usr/bin/env python3

import argparse
import json
import subprocess
import shutil
import os

parser = argparse.ArgumentParser()
parser.add_argument('--json', type=json.loads, required=True, help='the json input')
args, _ = parser.parse_known_args()

subprocess.run('rm -rf /output'.split())

subprocess.run('./eval_scripts/test.sh {0} {1} {2} {3}'.format(args.json['opts']['experiment'],
													args.json['opts']['num_folds'],
													args.json['opts']['anserini_path'],
													args.json['opts']['tune_params']).split())

files = os.listdir('runs')
for file in files:
	shutil.move(os.path.join('runs', file), '/output')
